apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myargoown
  annotations:
    github.com/project-slug: arboleda-alejandro/myargoown
    backstage.io/techdocs-ref: dir:.
  description: Personal ArgoCD deployment for managing Kubernetes applications
spec:
  type: service
  lifecycle: experimental
  owner: user:default/arboleda-alejandro
  system: gitops-platform
  dependsOn:
    - component:argo-helm-alejo

